on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions"
      - run: |
          yarn
          yarn build
      - run: |
          cd dist
          git switch -c gh-pages
          git add . -f
          git commit -m "release: github-pages"
          git push origin gh-pages
